[package]
name = "modules"
version = "0.1.0"
edition = "2021"

[lib]
name = "restaurant"
path = "src/lib.rs"

[[bin]]
name = "modules"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
